# Generated by Django 6.0.3 on 2026-03-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlıq")),
                ("content", models.TextField(verbose_name="Məzmun")),
                ("image", models.ImageField(upload_to="blog/", verbose_name="Şəkil")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma tarixi"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bloq yazısı",
                "verbose_name_plural": "Bloq yazıları",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ad Soyad")),
                ("email", models.EmailField(max_length=254, verbose_name="E-poçt")),
                ("subject", models.CharField(max_length=200, verbose_name="Mövzu")),
                ("message", models.TextField(verbose_name="Mesaj")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Əlaqə mesajı",
                "verbose_name_plural": "Əlaqə mesajları",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Sual")),
                ("answer", models.TextField(verbose_name="Cavab")),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ-lar",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlıq")),
                ("description", models.TextField(verbose_name="Təsvir")),
                (
                    "image",
                    models.ImageField(upload_to="services/", verbose_name="Şəkil"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Xidmət",
                "verbose_name_plural": "Xidmətlər",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ad Soyad")),
                ("comment", models.TextField(verbose_name="Rəy")),
                (
                    "rating",
                    models.IntegerField(default=5, verbose_name="Reytinq (1-5)"),
                ),
            ],
            options={
                "verbose_name": "Rəy",
                "verbose_name_plural": "Rəylər",
            },
        ),
    ]
